services:
  web:
    image: ghcr.io/thiagodsti/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8015:3000"
    depends_on:
      - server

  db:
    image: imresamu/postgis:17-3.5
    container_name: adventurelog-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - /mnt/docker/adventurelog/postgres:/var/lib/postgresql/data

  server:
    image: ghcr.io/thiagodsti/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8016:80"
      - "2525:2525"
    depends_on:
      - db
    volumes:
      - /mnt/docker/adventurelog/media:/code/media
